services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
      - 5050:5050
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64
    image: mysql:8.4.6
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_table
      MYSQL_USER: admin
      MYSQL_PASSWORD: oasis0903
    ports:
      - 3307:3306
