services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
      - 5050:5050
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.4.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_table
      MYSQL_USER: admin
      MYSQL_PASSWORD: oasis0903
    ports:
      - 3307:3306
